### ISSUE TITLE
Tested with logstash 1.5beta1?

### ISSUE THREAD

**Issue by dougmcclure** [jwconway/logstash-stanford-nlp#1]
Testing your plugin with my logstash 1.5beta1 install.  Any ideas?

 bin/logstash agent -f configs/nlp.conf --verbose
Using milestone 1 filter plugin 'nlp'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones {:level=>:warn}
The error reported is:
  cannot link Java class uk.co.jaywayco.Parser, probable missing dependency: uk/co/jaywayco/Parser : Unsupported major.minor version 52.0

 java -version
java version "1.7.0_25"
OpenJDK Runtime Environment (rhel-2.3.10.4.el6_4-x86_64)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)

**Comment by jwconway** [comment]
Yeah, i had similar when first using Stanford Core NLP. You need to upgrade the java version.

Stanford NLP Core libraries require Java Version 1.8+

http://nlp.stanford.edu/software/corenlp.shtml

Cheers
